baseURL = "https://blog.euxn.me/"
contentDir = "blog-entry"
defaultLayout = "entry"
enableEmoji = true
googleAnalytics = ""
languageCode = "en-us"
paginate = 20
staticDir = "blog-entry/static"
title = "Eutech Blog"
theme = "robust"
hasCjkLanguage = true

[params]
description = """
@euxn23 の技術ブログです。たまにレビュー記事も書きます。
"""

[outputs]
page = [ "HTML", "AMP" ]
